# Generated by Django 4.2.19 on 2025-03-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_deliveryroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('number_of_drivers', models.PositiveIntegerField()),
                ('total_packages', models.PositiveIntegerField()),
                ('avg_packages_per_driver', models.FloatField()),
                ('std_dev_min', models.FloatField()),
                ('std_dev_max', models.FloatField()),
                ('package_distribution', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryRoute',
        ),
    ]
