# Generated by Django 4.2.19 on 2025-03-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_summary_delete_deliveryroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField()),
                ('route', models.TextField()),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='management.summary')),
            ],
        ),
    ]
