# Generated by Django 4.2.19 on 2025-03-30 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkforce',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.depot'),
        ),
    ]
