# Generated by Django 4.2.19 on 2025-03-31 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_dailyworkforce_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkforce',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workforces', to='management.summary'),
        ),
    ]
