# Generated by Django 4.2.19 on 2025-04-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_summary_depot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailydistribution',
            unique_together={('session', 'city')},
        ),
    ]
