# Generated by Django 4.2.19 on 2025-04-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_dailydistribution_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailydistribution',
            unique_together=set(),
        ),
    ]
